server:
  port: 9090

spring:
  application:
    name: demoservice
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/