server:
  port: 9090

spring:
  application:
    name: demoservice
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PW}
    virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}