services:
    frontend:
        # image: mingli99/frontend:latest
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '80:80'
        environment:
            - REACT_APP_GATEWAY_URL=http://localhost:8085
            - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
            - REACT_APP_SUPABASE_KEY=${JWT_SECRET}
        networks:
            - suara-cloud
        restart: always
        depends_on:
            - gateway

    rabbitmq:
        image: rabbitmq:management
        ports:
            - '5672:5672'
            - '15672:15672'
            - '1883:1883'
        environment:
            - 'RABBITMQ_DEFAULT_PASS=secret'
            - 'RABBITMQ_DEFAULT_USER=myuser'
        networks:
            - suara-cloud
        command: |
            bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"
        restart: always

    eureka:
        image: mingli99/eureka:latest
        ports:
            - '8761:8761'
        networks:
            - suara-cloud
        restart: always

    gateway:
        image: mingli99/gateway:latest
        # build:
        #     context: ./Gateway
        #     dockerfile: Dockerfile
        ports:
            - '8085:8085'
        networks:
            - suara-cloud
        environment:
            - EUREKA_URL=http://eureka:8761/eureka/
        restart: always
        depends_on:
            - eureka

    demo-api:
        image: mingli99/demo-api:latest
        ports:
            - '9090:9090'
        networks:
            - suara-cloud
        environment:
            - RABBITMQ_URL=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=myuser
            - RABBITMQ_PW=secret
            - EUREKA_URL=http://eureka:8761/eureka/
        restart: always
        depends_on:
            - eureka
            - rabbitmq

    song-service:
        # image: mingli99/songservice:latest
        build:
            context: ./SongService
            dockerfile: Dockerfile
        ports:
            - '9091:9091'
        networks:
            - suara-cloud
        environment:
            - RABBITMQ_URL=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=myuser
            - RABBITMQ_PW=secret
            - EUREKA_URL=http://eureka:8761/eureka/
            - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
        restart: always
        depends_on:
            - eureka
            - rabbitmq

    song-meta-service:
        # image: mingli99/songmetaservice:latest
        build:
            context: ./SongMetaService
            dockerfile: Dockerfile
        ports:
            - '9092:9092'
        networks:
            - suara-cloud
        environment:
            - RABBITMQ_URL=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=myuser
            - RABBITMQ_PW=secret
            - EUREKA_URL=http://eureka:8761/eureka/
            - DATABASE_URL=${SONG_META_DATABASE_URL}
            - DATABASE_USERNAME=${SONG_META_DATABASE_USERNAME}
            - DATABASE_PASSWORD=${SONG_META_DATABASE_PASSWORD}
        restart: always
        depends_on:
            - eureka

    auth-service:
        image: mingli99/authservice:latest
        ports:
            - '8086:8086'
        networks:
            - suara-cloud
        environment:
            - RABBITMQ_URL=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=myuser
            - RABBITMQ_PW=secret
            - EUREKA_URL=http://eureka:8761/eureka/
            - JWT_SECRET=${JWT_SECRET}
        restart: always
        depends_on:
            - eureka

    user-service:
        image: mingli99/userservice:latest
        # build:
        #     context: ./UserService
        #     dockerfile: Dockerfile
        ports:
            - '8087:8087'
        networks:
            - suara-cloud
        environment:
            - RABBITMQ_URL=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=myuser
            - RABBITMQ_PW=secret
            - EUREKA_URL=http://eureka:8761/eureka/
            - DATABASE_URL=${USER_SERVICE_DATABASE_URL}
            - DATABASE_USERNAME=${USER_SERVICE_DATABASE_USERNAME}
            - DATABASE_PASSWORD=${USER_SERVICE_DATABASE_PASSWORD}
        restart: always
        depends_on:
            - eureka

    logging-service:
        image: mingli99/loggingservice:latest
        ports:
            - '8088:8088'
        networks:
            - suara-cloud
        environment:
            - RABBITMQ_URL=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=myuser
            - RABBITMQ_PW=secret
            - EUREKA_URL=http://eureka:8761/eureka/
        restart: always
        depends_on:
            - eureka

networks:
    suara-cloud:
        driver: bridge
