services:
    frontend:
        image: mingli99/frontend:latest
        ports:
            - '3000:3000'
        networks:
            - suara-cloud
        environment:
            REACT_APP_GATEWAY_URL: 'http://localhost:8085'
        restart: always
        depends_on:
            - gateway

    rabbitmq:
        image: rabbitmq:management
        ports:
            - '5672:5672'
            - '15672:15672'
            - '1883:1883'
        environment:
            - 'RABBITMQ_DEFAULT_PASS=secret'
            - 'RABBITMQ_DEFAULT_USER=myuser'
        networks:
            - suara-cloud
        command: |
            bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"
        restart: always

    eureka:
        image: mingli99/eureka:latest
        ports:
            - '8761:8761'
        networks:
            - suara-cloud
        restart: always

    gateway:
        image: mingli99/gateway:latest
        ports:
            - '8085:8085'
        networks:
            - suara-cloud
        environment:
            - EUREKA_URL=http://eureka:8761/eureka/
        restart: always
        depends_on:
            - eureka

    demo-api:
        image: mingli99/demo-api:latest
        ports:
            - '9090:9090'
        networks:
            - suara-cloud
        environment:
            - RABBITMQ_URL=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=myuser
            - RABBITMQ_PW=secret
            - EUREKA_URL=http://eureka:8761/eureka/
        restart: always
        depends_on:
            - eureka
            - rabbitmq

    song-service:
        image: mingli99/songservice:latest
        ports:
            - '9091:9091'
        networks:
            - suara-cloud
        environment:
            - RABBITMQ_URL=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=myuser
            - RABBITMQ_PW=secret
            - EUREKA_URL=http://eureka:8761/eureka/
        restart: always
        depends_on:
            - eureka
            - rabbitmq

    auth-service:
        image: mingli99/authservice:latest
        ports:
            - '9092:9092'
        networks:
            - suara-cloud
        environment:
            - RABBITMQ_URL=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USER=myuser
            - RABBITMQ_PW=secret
            - EUREKA_URL=http://eureka:8761/eureka/
            - JWT_SECRET=JJ5KcwkeMPtdCIqTytKoM5GqgY/2gtXSTS7coCKH9uteTp6sWel6UyRb8g+iFxh1nlYJJ+AS3CSu4eitpXn/+g==
        restart: always
        depends_on:
            - eureka
            - rabbitmq
networks:
    suara-cloud:
        driver: bridge
