services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_USER=myuser
    ports:
      - '5672:5672'
      - '15672:15672'
      - '1883:1883'
    command: |
      bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"

