server:
  port: 8085

spring:
  application:
    name: Gateway
  cloud:
    gateway:
       routes:
        - id: demoservice
          uri: lb://DEMOSERVICE
          predicates:
            - Path=/demo/**
        - id: songservice
          uri: lb://SONGSERVICE
          predicates:
            - Path=/songs/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true