server:
  port: 8085

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: demoservice
          uri: lb://demoservice
          predicates:
            - Path=/demo/**, /api/**
        - id: songservice
          uri: lb://songservice
          predicates:
            - Path=/songs/**
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/users/**
        - id: songmetaservice
          uri: lb://songmetaservice
          predicates:
            - Path=/songmeta/**
        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/auth/**
        - id: loggingservice
          uri: lb://loggingservice
          predicates:
            - Path=/logging/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true