server:
  port: 8085

spring:
  application:
    name: Gateway
  cloud:
    gateway:
       routes:
        - id: demoservice
          uri: lb://DEMOSERVICE
          predicates:
            - Path=/demo/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    registerWithEureka: true
    fetchRegistry: true