apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: eureka-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: eureka
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
