apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        io.kompose.service: frontend
    name: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: frontend
    template:
        metadata:
            labels:
                io.kompose.service: frontend
        spec:
            containers:
                - env:
                      - name: REACT_APP_GATEWAY_URL
                        value: http://gateway:8085
                  image: mingli99/frontend:latest
                  name: frontend
                  ports:
                      - containerPort: 3000
                        protocol: TCP
            restartPolicy: Always
