apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: logging-service-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: logging-service
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
