apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: song-meta-service-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: song-meta-service
    minReplicas: 1
    maxReplicas: 20
    targetCPUUtilizationPercentage: 50
