apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        io.kompose.service: song-service
    name: song-service
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: song-service
    template:
        metadata:
            labels:
                io.kompose.service: song-service
        spec:
            containers:
                - env:
                      - name: EUREKA_URL
                        valueFrom:
                            configMapKeyRef:
                                name: song-service-config
                                key: EUREKA_URL
                      - name: RABBITMQ_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: song-service-config
                                key: RABBITMQ_PORT
                      - name: RABBITMQ_PW
                        valueFrom:
                            secretKeyRef:
                                name: song-service-secrets
                                key: RABBITMQ_PW
                      - name: RABBITMQ_URL
                        valueFrom:
                            configMapKeyRef:
                                name: song-service-config
                                key: RABBITMQ_URL
                      - name: RABBITMQ_USER
                        valueFrom:
                            secretKeyRef:
                                name: song-service-secrets
                                key: RABBITMQ_USER
                      - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
                        value: 'true'
                      - name: EUREKA_INSTANCE_HOSTNAME
                        valueFrom:
                            configMapKeyRef:
                                name: song-service-config
                                key: EUREKA_INSTANCE_HOSTNAME
                      - name: AZURE_STORAGE_CONNECTION_STRING
                        valueFrom:
                            secretKeyRef:
                                name: song-service-secrets
                                key: AZURE_STORAGE_CONNECTION_STRING
                  image: mingli99/songservice:latest
                  name: song-service
                  ports:
                      - containerPort: 9091
                        protocol: TCP
            restartPolicy: Always
