server:
  port: 9091

spring:
  application:
    name: songservice
  rabbitmq:
    host: ${RABBITMQ_URL:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:myuser}
    password: ${RABBITMQ_PW:secret}
    virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
