name: CI-CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - dev

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                folder: [frontend]

        env:
            REACT_APP_GATEWAY_URL: ${{ secrets.REACT_APP_GATEWAY_URL }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Navigate to folder and install dependencies
              run: |
                  cd ${{ matrix.folder }}
                  npm install

            - name: Run Jest tests with coverage
              run: |
                  cd ${{ matrix.folder }}
                  npm test -- --coverage

            - name: Upload Jest Coverage Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: jest-coverage
                  path: frontend/coverage/lcov.info
                  retention-days: 1

    sonarqube:
        name: SonarQube
        runs-on: ubuntu-latest
        needs: build-and-test
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Download Jest Coverage Artifact
              uses: actions/download-artifact@v4
              with:
                  name: jest-coverage
                  path: frontend/coverage

            - name: Debug Coverage File
              run: ls -lah frontend/coverage/ && cat frontend/coverage/lcov.info | head -n 20

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v5
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    docker-build-and-push:
        name: Build & Push Docker Images
        runs-on: ubuntu-latest
        needs: build-and-test

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Find All Services with Dockerfile
              id: find-services
              run: |
                  # This finds every Dockerfile and extracts its parent folder name
                  folders=$(find . -type f -name "Dockerfile" -exec dirname {} \; | cut -c 3- | jq -R -s -c 'split("\n")[:-1]')
                  echo "services=$folders" >> $GITHUB_ENV

            - name: Build and Push Docker Images
              run: |
                  # 'services' environment variable is set by the step above
                  for service in $(echo $services | jq -r '.[]'); do
                    # Convert folder name to lowercase
                    lowercase_service="$(echo "$service" | tr '[:upper:]' '[:lower:]')"

                    # Special case: If the lowercase folder name is 'demoservice', rename to 'demo-api'
                    if [ "$lowercase_service" = "demoservice" ]; then
                      image_name="demo-api"
                    else
                      image_name="$lowercase_service"
                    fi

                    DOCKER_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/$image_name:latest"
                    echo "Building and pushing $DOCKER_IMAGE from folder '$service'..."

                    docker build -t "$DOCKER_IMAGE" "$service"
                    docker push "$DOCKER_IMAGE"
                  done
