name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - setup

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [frontend] # List all directories with `package.json`

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Navigate to the folder
      - name: Navigate to folder and install dependencies
        run: |
          cd ${{ matrix.folder }}
          npm install

      # Run tests with coverage
      - name: Run tests
        run: |
          cd ${{ matrix.folder }}
          npm test
