name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [frontend]

    env:
      REACT_APP_GATEWAY_URL: ${{ secrets.REACT_APP_GATEWAY_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Navigate to folder and install dependencies
        run: |
          cd ${{ matrix.folder }}
          npm install

      - name: Run tests
        run: |
          cd ${{ matrix.folder }}
          npm test

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
